CREATE TABLE IF NOT EXISTS flower_flow_checkpoint (
    flow_type VARCHAR(100) NOT NULL,
    flow_key VARCHAR(200) NOT NULL,
    state VARCHAR(20) NOT NULL,
    current_step_id VARCHAR(200),
    current_step_no INTEGER NOT NULL,
    current_step_entered BOOLEAN NOT NULL,
    persistence VARCHAR(20) NOT NULL,
    worker_name VARCHAR(100),
    updated_at_millis BIGINT NOT NULL,
    definition_version VARCHAR(100),
    PRIMARY KEY (flow_type, flow_key)
);

CREATE INDEX IF NOT EXISTS idx_flower_checkpoint_active
    ON flower_flow_checkpoint (state, updated_at_millis);

CREATE INDEX IF NOT EXISTS idx_flower_checkpoint_worker_active
    ON flower_flow_checkpoint (worker_name, state, updated_at_millis);

CREATE TABLE IF NOT EXISTS sample_order (
    order_id VARCHAR(100) PRIMARY KEY,
    status VARCHAR(40) NOT NULL,
    payment_received BOOLEAN NOT NULL,
    inventory_reserved BOOLEAN NOT NULL,
    shipped BOOLEAN NOT NULL,
    completed BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS sample_audit_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_type VARCHAR(80) NOT NULL,
    message VARCHAR(500) NOT NULL,
    created_at TIMESTAMP NOT NULL
);
